# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hashtag_pb2 as hashtag__pb2


class HashtagsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendTweet = channel.unary_unary(
        '/Hashtags/sendTweet',
        request_serializer=hashtag__pb2.TweetRequest.SerializeToString,
        response_deserializer=hashtag__pb2.Empty.FromString,
        )
    self.getTweetsByHashtag = channel.unary_unary(
        '/Hashtags/getTweetsByHashtag',
        request_serializer=hashtag__pb2.TweetHashtagRequest.SerializeToString,
        response_deserializer=hashtag__pb2.TweetsList.FromString,
        )
    self.getTweetSentiment = channel.unary_unary(
        '/Hashtags/getTweetSentiment',
        request_serializer=hashtag__pb2.TweetHashtagRequest.SerializeToString,
        response_deserializer=hashtag__pb2.TweetSentiment.FromString,
        )


class HashtagsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sendTweet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getTweetsByHashtag(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getTweetSentiment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HashtagsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendTweet': grpc.unary_unary_rpc_method_handler(
          servicer.sendTweet,
          request_deserializer=hashtag__pb2.TweetRequest.FromString,
          response_serializer=hashtag__pb2.Empty.SerializeToString,
      ),
      'getTweetsByHashtag': grpc.unary_unary_rpc_method_handler(
          servicer.getTweetsByHashtag,
          request_deserializer=hashtag__pb2.TweetHashtagRequest.FromString,
          response_serializer=hashtag__pb2.TweetsList.SerializeToString,
      ),
      'getTweetSentiment': grpc.unary_unary_rpc_method_handler(
          servicer.getTweetSentiment,
          request_deserializer=hashtag__pb2.TweetHashtagRequest.FromString,
          response_serializer=hashtag__pb2.TweetSentiment.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Hashtags', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
