# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hashtag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hashtag.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rhashtag.proto\"\x07\n\x05\x45mpty\"/\n\x0cTweetRequest\x12\r\n\x05tweet\x18\x01 \x01(\t\x12\x10\n\x08tweet_id\x18\x02 \x01(\x05\"&\n\x13TweetHashtagRequest\x12\x0f\n\x07hashtag\x18\x01 \x01(\t\"-\n\nTweetsList\x12\x0f\n\x07hashtag\x18\x01 \x01(\t\x12\x0e\n\x06tweets\x18\x02 \x03(\t\"#\n\x0eTweetSentiment\x12\x11\n\tsentiment\x18\x01 \x01(\t2\xa9\x01\n\x08Hashtags\x12$\n\tsendTweet\x12\r.TweetRequest\x1a\x06.Empty\"\x00\x12\x39\n\x12getTweetsByHashtag\x12\x14.TweetHashtagRequest\x1a\x0b.TweetsList\"\x00\x12<\n\x11getTweetSentiment\x12\x14.TweetHashtagRequest\x1a\x0f.TweetSentiment\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=24,
)


_TWEETREQUEST = _descriptor.Descriptor(
  name='TweetRequest',
  full_name='TweetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tweet', full_name='TweetRequest.tweet', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tweet_id', full_name='TweetRequest.tweet_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=73,
)


_TWEETHASHTAGREQUEST = _descriptor.Descriptor(
  name='TweetHashtagRequest',
  full_name='TweetHashtagRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hashtag', full_name='TweetHashtagRequest.hashtag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=113,
)


_TWEETSLIST = _descriptor.Descriptor(
  name='TweetsList',
  full_name='TweetsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hashtag', full_name='TweetsList.hashtag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tweets', full_name='TweetsList.tweets', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=160,
)


_TWEETSENTIMENT = _descriptor.Descriptor(
  name='TweetSentiment',
  full_name='TweetSentiment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentiment', full_name='TweetSentiment.sentiment', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=197,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['TweetRequest'] = _TWEETREQUEST
DESCRIPTOR.message_types_by_name['TweetHashtagRequest'] = _TWEETHASHTAGREQUEST
DESCRIPTOR.message_types_by_name['TweetsList'] = _TWEETSLIST
DESCRIPTOR.message_types_by_name['TweetSentiment'] = _TWEETSENTIMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'hashtag_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

TweetRequest = _reflection.GeneratedProtocolMessageType('TweetRequest', (_message.Message,), dict(
  DESCRIPTOR = _TWEETREQUEST,
  __module__ = 'hashtag_pb2'
  # @@protoc_insertion_point(class_scope:TweetRequest)
  ))
_sym_db.RegisterMessage(TweetRequest)

TweetHashtagRequest = _reflection.GeneratedProtocolMessageType('TweetHashtagRequest', (_message.Message,), dict(
  DESCRIPTOR = _TWEETHASHTAGREQUEST,
  __module__ = 'hashtag_pb2'
  # @@protoc_insertion_point(class_scope:TweetHashtagRequest)
  ))
_sym_db.RegisterMessage(TweetHashtagRequest)

TweetsList = _reflection.GeneratedProtocolMessageType('TweetsList', (_message.Message,), dict(
  DESCRIPTOR = _TWEETSLIST,
  __module__ = 'hashtag_pb2'
  # @@protoc_insertion_point(class_scope:TweetsList)
  ))
_sym_db.RegisterMessage(TweetsList)

TweetSentiment = _reflection.GeneratedProtocolMessageType('TweetSentiment', (_message.Message,), dict(
  DESCRIPTOR = _TWEETSENTIMENT,
  __module__ = 'hashtag_pb2'
  # @@protoc_insertion_point(class_scope:TweetSentiment)
  ))
_sym_db.RegisterMessage(TweetSentiment)



_HASHTAGS = _descriptor.ServiceDescriptor(
  name='Hashtags',
  full_name='Hashtags',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=200,
  serialized_end=369,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendTweet',
    full_name='Hashtags.sendTweet',
    index=0,
    containing_service=None,
    input_type=_TWEETREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getTweetsByHashtag',
    full_name='Hashtags.getTweetsByHashtag',
    index=1,
    containing_service=None,
    input_type=_TWEETHASHTAGREQUEST,
    output_type=_TWEETSLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getTweetSentiment',
    full_name='Hashtags.getTweetSentiment',
    index=2,
    containing_service=None,
    input_type=_TWEETHASHTAGREQUEST,
    output_type=_TWEETSENTIMENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HASHTAGS)

DESCRIPTOR.services_by_name['Hashtags'] = _HASHTAGS

# @@protoc_insertion_point(module_scope)
